### ISSUE TITLE
Warning in CardReaderProviderApi

### ISSUE THREAD

**Issue by ingopaulsen** [gematik/ref-OpenHealthCardKit#10]
I got this warning:

CardReaderProviderApi/Card/CardError.swift:28:10: warning: associated value 'objcError' of 'Sendable'-conforming enum 'CardError' has non-sendable type 'NSException?'
    case objcError(NSException?)

**Comment by sigabrtz** [comment]
Thanks for the pointer.
We plan to incorporate structured concurrency into this framework within the next weeks. That should also address these types of warnings.
