### ISSUE TITLE
Pin length check not working on test cards

### ISSUE THREAD

**Issue by mdelete** [gematik/ref-OpenHealthCardKit#15]
The old pin length check is: `oldPin.count > 5 && oldPin.count <= 6` which is equivalent and can be reduced to: `oldPin.count == 6`, which was probably not intended, as test cards have 5 digit initial pins and therefore the pin cannot be changed.

Proposed patch enclosed:
[pin_len_check.patch](https://github.com/gematik/ref-OpenHealthCardKit/files/14129030/pin_len_check.patch)

**Comment by sigabrtz** [comment]
You are correct. Thank you for the pointer.
We'll apply the patch immediately and give you a ping

**Comment by sigabrtz** [comment]
We made a GitHub Release containing your patch. The AppStore release is pending. Thanks again
