### ISSUE TITLE
Where can I find the Android version of this library?

### ISSUE THREAD

**Issue by ilovemyfamilyforever** [gematik/ref-OpenHealthCardKit#18]
I found some libraries such as ref-OpenHealthCard-Common-Android, ref-CardReaderProvider-NFC-Android

**Comment by mfiebig** [comment]
We are working on that, for the time being, you might find the android E-Rezept-App source (https://github.com/gematik/E-Rezept-App-Android) useful. The library will be split out of the current application.

**Comment by ilovemyfamilyforever** [comment]
@mfiebig We want to parse EF.GVD, EF.VD and EF.PD from eGK for the e-Rezept.

**Comment by ZuSe** [comment]
Is there any update on the topic?
We would be interested to use the eGK as "Online-Check-In" option (besides GesundheitsID) within our app :)

**Comment by mfiebig** [comment]
Hi, I can't give you any reliable date. We are still planning to do this, current estimation is early to mid 2025.

**Comment by ZuSe** [comment]
Thanks for the info!
