### ISSUE TITLE
Issue reading EF.PD and EF.VD

### ISSUE THREAD

**Issue by etjenymeraj** [gematik/ref-OpenHealthCardKit#24]
In the current project Im reading a lot of values from root folder such as gdo atr etc. This reading works just fine. 

However when I switch to HCA folder (DF.HCA) and I use the already built command methods from the library to read (EF.PD) the data bytes I receive or the hex code is incomplete. 

My EF.PD command printed

First PD command - cla: 00 ins: B0 p1: 82 p2: 00 ne: 256
Second PD command - cla: 00 ins: B0 p1: 00 p2: 08 ne: 65536

I tried running commands in this order but also just running second command directly. The result is the same. 

Can you advise any potential solutions here?

**Comment by etjenymeraj** [comment]
func selectHcaCommand() -> CommandType {
        let applicationIdentifier = EgkFileSystem.DF.HCA.aid
        return HealthCardCommand.Select.selectFile(with: applicationIdentifier)
    }

**Comment by etjenymeraj** [comment]
func readHCAPDCommandShort() throws -> CommandType {
        guard let shortFileIdentifier = EgkFileSystem.EF.hcaPD.sfid else { throw HealthCardCommandError.hcaPDUnavailable  }
        return try HealthCardCommand.Read.readFileCommand(with: shortFileIdentifier, ne: APDU.expectedLengthWildcardShort)
    }

    func readHCAPDCommand() throws -> CommandType {
        try HealthCardCommand.Read.readFileCommand(ne: APDU.expectedLengthWildcardExtended, offset: 2)
    }

**Comment by etjenymeraj** [comment]
try await card.selectHca()

        let hcaPDDataShort = try await card.readHCAPDShort()
        print("##########")
        print("NFC DATA PD Hex \(hcaPDDataShort!.hexString)")
        print("##########")
        print("NFC DATA PD Bytes \([UInt8](hcaPDDataShort!))")

        let hcaPDData     = try await card.readHCAPD()
        print("##########")
        print("NFC DATA PD Hex \(hcaPDData!.hexString)")
        print("##########")
        print("NFC DATA PD Bytes \([UInt8](hcaPDData!))")

**Comment by etjenymeraj** [comment]
extension Data {
    var hexString: String {
        Array(self)
            .map { $0.hexString }
            .joined(separator: "")
    }
}

**Comment by etjenymeraj** [comment]
extension UInt8 {
    var hexString: String {
        var result = String(self, radix: 16, uppercase: true)
        
        while result.count < 2 {
            result = "0" + result
        }
        
        return result
    }
}

**Comment by etjenymeraj** [comment]
Expected response from the pdf

1F8B08000000000000008D914D4FC3300C86FFCA94FBEA666CB0213708313E26AD0C3131B84DA1356B459BA2241D1FBF9D03EED8C686387049F2DACEF35A369EBC95456B49D6E59589840C42D1229354696E1691184D27ED7EBF3768CB9E6839AF4DAA8BCA5024DEC98913857767F31BFE5A9129F224A35983E1DB7AE24A3E1EE271EB6C18CF67E7B7D3D1E43A12BD60E5C09EC64522F3FEE518E0D5050B2AB5CF9F8394E049C3D2A50EFEC18625F384C29D9CDD53663E1AAAA194A10CBB877280F03B872B0BA3F0921E6BEB1D93EB52C9413F0CA5EC20EC85715659A34B52635F336A2DF05A27D9EA15D78E1B78D60C6F377E08DB14F35D921594645EC50D76AB70EAAD768ECC696A896F6EA972BEA0DC7FE8AC509DEEE0E008612F8613EBD54541C671730B8446E29897A3F0BECA8CE3B242F394C8F21E490D11FE0A237C7F59FBABF8336B90DE06089B185EE9DA99BA2C79AEDD43841DB92DFA691C36C384FD85FC6795EA0B6B3E2A8C890200009000

**Comment by etjenymeraj** [comment]
Actual result (only 2 bites missing)

1F8B08000000000000008D524D4FC3300CFD2B55EED45D47812137081882498C210683DB145AB35624294AD2F1F1EB71070C86387071F29E9DE7273B78F06274B424E7EBC6E6A2172722225B34656D17B9184D275B7B7BD960AB9789C807654BA51B4BB978252F0E24DE1CCF2FF9694356D74545B34E864F17882B39DC8DCFA3E3E1783E3BB99A8E2617B9C8E2B4EBC03DADCF4515C2D33EC0B38F176454A81FE392E041C1D297A60BB0E47A21F187AEDB40763E1ACAEB244D777706DB591FE1770E57F6ACC453BA6F5DF0ECAA35B23718F49334491136689C35CE2A4372A86C4D9AD53E315EA8A25ADDC6AD670F46598BB02659DC1795A6A20A72DC69AE114E8353DE933D2C1DF1C97E1A1F34D5E14D555AA6693FC91036389CB820CF94615F0B840EE039CF5DE26D5359CF455AF170C9F18AD828C25F34C2C793CFEEF2C829F3409AD3115331C25702CF54EB6D6B0CCFB5B79D20FCC0EBAA6FF3F0354DD8DC08FCE31FC87740FC876B6A0200009000

**Comment by etjenymeraj** [comment]
Leaving this for anyone else here. The above commands work fine. The format you get is gzip. So you need to decompress the gzip. Then you get data which you need to convert to string. Not using utf 8 but rather 

String(data: unzippedData!, encoding: .windowsCP1250))")

**Comment by priska96** [comment]
@etjenymeraj Hey can I ask how you decoded the hexString that is returned from the PD file?

**Comment by etjen-redcare** [comment]
Update I ended up not using windowsCP1250 after all. I just let the system XML parser to decode the xml data. just don't forget to gunzip first to create the Data object then pass it to xml parser.
