### ISSUE TITLE
Error executing "bundle exec fastlane setup"

### ISSUE THREAD

**Issue by bogdanpralea** [gematik/ref-OpenHealthCardKit#7]
Hello,
I have found your SDK and also your DemoApp for this SDK but I am not able to run either of them.

After executing the command " bundle exec fastlane setup" I get this error:
" Exit status of command 'carthage build --no-use-binaries --platform iOS --configuration Debug --cache-builds' was 1 instead of 0.
*** No cache found for BigInt, building with all downstream dependencies
*** No cache found for DataKit, building with all downstream dependencies
*** No cache found for ref-GemCommonsKit, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/kw/5wzswvfs2rqdc1dw9tt3vts40000gn/T/carthage-xcodebuild.WL9lbn.log
*** Building scheme "BigInt-iOS" in BigInt.xcworkspace
A shell task (/usr/bin/xcrun lipo -create /Users/bogdanpralea/Library/Caches/org.carthage.CarthageKit/DerivedData/14.3_14E222b/BigInt/v5.3.0/Build/Intermediates.noindex/ArchiveIntermediates/BigInt-iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/BigInt.framework/BigInt /Users/bogdanpralea/Library/Caches/org.carthage.CarthageKit/DerivedData/14.3_14E222b/BigInt/v5.3.0/Build/Products/Debug-iphonesimulator/BigInt.framework/BigInt -output /Users/bogdanpralea/Documents/Study/TestApp/Carthage/Build/iOS/BigInt.framework/BigInt) failed with exit code 1:
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/bogdanpralea/Library/Caches/org.carthage.CarthageKit/DerivedData/14.3_14E222b/BigInt/v5.3.0/Build/Intermediates.noindex/ArchiveIntermediates/BigInt-iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/BigInt.framework/BigInt and /Users/bogdanpralea/Library/Caches/org.carthage.CarthageKit/DerivedData/14.3_14E222b/BigInt/v5.3.0/Build/Products/Debug-iphonesimulator/BigInt.framework/BigInt have the same architectures (arm64) and can't be in the same fat output file

Building universal frameworks with common architectures is not possible. The device and simulator slices for "BigInt" both build for: arm64
Rebuild with --use-xcframeworks to create an xcframework bundle instead."

The log looks like this: 
"/Users/bogdanpralea/Documents/Study/TestApp/Carthage/Checkouts/BigInt/BigInt.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'BigInt-iOS' from project 'BigInt')
** BUILD SUCCEEDED **"

After searching a bit I have found that this is a problem with Carthage and the recommended solution on their forums(https://github.com/Carthage/Carthage/issues/3333) is by using a script.
So I created the script and tried to run it with " sh carthage.sh update --platform iOS --use-xcframeworks --no-use-binaries" and it still fails with the error:
"*** Building scheme "NFCCardReaderProvider" in OpenHealthCardKit.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/bogdanpralea/Documents/Study/TestApp/Carthage/Checkouts/ref-OpenHealthCardKit/OpenHealthCardKit.xcodeproj -scheme NFCCardReaderProvider -configuration Release -derivedDataPath /Users/bogdanpralea/Library/Caches/org.carthage.CarthageKit/DerivedData/14.3_14E222b/ref-OpenHealthCardKit/1.0.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/kw/5wzswvfs2rqdc1dw9tt3vts40000gn/T/ref-OpenHealthCardKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO FRAMEWORK_SEARCH_PATHS=$(inherited)\ /var/folders/kw/5wzswvfs2rqdc1dw9tt3vts40000gn/T/carthage-xcframework-xQQx (launched in /Users/bogdanpralea/Documents/Study/TestApp/Carthage/Checkouts/ref-OpenHealthCardKit)"

and the error in the log : "
/Users/bogdanpralea/Documents/Study/TestApp/Carthage/Checkouts/ref-OpenHealthCardKit/Sources/NFCCardReaderProvider/Reader/NFCCardReader.swift:71:27: error: cannot assign to property: 'value' is a get-only property
        cardPresenceBlock.value = block
        ~~~~~~~~~~~~~~~~~~^~~~~"
....



** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64 (in target 'NFCCardReaderProvider' from project 'OpenHealthCardKit')
	SwiftCompile normal arm64 Compiling\ NFCCard.swift,\ NFCCardChannel.swift,\ NFCCardReader+NFCTagReaderSessionDelegate.swift,\ NFCCardReader.swift,\ NFCCardReaderController.swift,\ NFCCardReaderProvider.swift,\ NFCISO7816APDU+CommandType.swift /Users/bogdanpralea/Documents/Study/TestApp/Carthage/Checkouts/ref-OpenHealthCardKit/Sources/NFCCardReaderProvider/Card/NFCCard.swift /Users/bogdanpralea/Documents/Study/TestApp/Carthage/Checkouts/ref-OpenHealthCardKit/Sources/NFCCardReaderProvider/Card/NFCCardChannel.swift /Users/bogdanpralea/Documents/Study/TestApp/Carthage/Checkouts/ref-OpenHealthCardKit/Sources/NFCCardReaderProvider/Reader/NFCCardReader+NFCTagReaderSessionDelegate.swift /Users/bogdanpralea/Documents/Study/TestApp/Carthage/Checkouts/ref-OpenHealthCardKit/Sources/NFCCardReaderProvider/Reader/NFCCardReader.swift /Users/bogdanpralea/Documents/Study/TestApp/Carthage/Checkouts/ref-OpenHealthCardKit/Sources/NFCCardReaderProvider/Reader/NFCCardReaderController.swift /Users/bogdanpralea/Documents/Study/TestApp/Carthage/Checkouts/ref-OpenHealthCardKit/Sources/NFCCardReaderProvider/Provider/NFCCardReaderProvider.swift /Users/bogdanpralea/Documents/Study/TestApp/Carthage/Checkouts/ref-OpenHealthCardKit/Sources/NFCCardReaderProvider/Card/NFCISO7816APDU+CommandType.swift (in target 'NFCCardReaderProvider' from project 'OpenHealthCardKit')
(2 failures)
"

Can you help me with this ?
Thanks!
[carthage-xcodebuild.924P9r.log](https://github.com/gematik/ref-OpenHealthCardKit/files/11464608/carthage-xcodebuild.924P9r.log)
[carthage-xcodebuild.WL9lbn.log](https://github.com/gematik/ref-OpenHealthCardKit/files/11464611/carthage-xcodebuild.WL9lbn.log)

**Comment by sigabrtz** [comment]
Hi,
the documentation/Readme is outdatet (we will change that soon).
Executing `make setup` in the project's root directory should set up the project (`brew` will be needed).

Does the error continue to exist afterwards?

**Comment by sigabrtz** [comment]
I close this due to inactivity.
Let us know whether the problem persists.
